### ISSUE TITLE
Asana integration: Restrict to Last Commit

### ISSUE THREAD

**Issue by aurelijusrozenas** [github/github-services#1005]
I set up integration with Asana, checked option "Restrict to Last Commit", but in Asana I still get one comment per commit. I was under impression that I should get only one comment per push, was I wrong?

**Comment by kdaigle** [comment]
It appears that that is a bug with the Asana service. It should read "Restrict to Last Comment" and the config option isn't setup correctly. https://github.com/github/github-services/commit/01e96e3f7347316dcb635d74dcd86ec67d3d98f4

The bug is that the boolean configuration variable is misnamed and then not being used by the larger service. We'll leave this open in hopes someone in the community can help fix this!

**Comment by mikemcquaid** [comment]
We may accept a PR for this but I'm closing this out for now.
