### ISSUE TITLE
There needs to be an easier way to configure webhooks events

### ISSUE THREAD

**Issue by FichteFoll** [github/github-services#1025]
I'm not sure if this is the right repo, but it's at least related.

Basically, if I want to create an IRC webhook that receives pull request and especially issue notifications I must use the API (and curl) to do so manually, which always involves trial and error because I never use the API outside of that. I wanted to update the description for the IRC webhook that better shows how to do it, ~~but I am simply unable to remove the `push` event for some reason. It's probably trivial, but it shouldn't be an issue in the first place.~~ Can't do "remove_events" and "add_events" in the same request apparently.

What you currently need to do is:

1. Find out how to change webhook events in the first place (I did that probably a year ago by asking via email)
2. Find the docs for webhooks in the API [here](https://developer.github.com/v3/repos/hooks/#edit-a-hook)
3. `curl -u USERNAME -i https://api.github.com/repos/USERORORG/REPONAME/hooks`
4. Find the id of the the webhook you want to change
5. `curl -u USERNAME -i https://api.github.com/repos/USERORORG/REPONAME/hooks/ID --request PATCH --data "{\"remove_events\": [\"push\"]}"`
6. `curl -u USERNAME -i https://api.github.com/repos/USERORORG/REPONAME/hooks/ID --request PATCH --data "{\"add_events\": [\"issues\"]}"` (because it apparently doesn't work together)

There needs to be a better way.

Related: #999, #963

**Comment by FichteFoll** [comment]
By the way, I didn't find docs on the available events. They are not in the related docs and not in the sources of this repo either, last time I checked. It would be nice if you could add those at least to the docs but also make available in some kind of GUI when this issue gets tackled.

**Comment by kdaigle** [comment]
Hey @FichteFoll! Thanks for this feedback. We did update the UI for choosing events for webhooks but we don't have any immediate plans to tackle the same level of changes for GitHub services.

You can view the supported events for services by making an API call to https://api.github.com/hooks.

Because this isn't actually an issue with `github-services` and more of an issue with GitHub.com, I'm going to share this with the larger team I'm on so we can see about fixing it in the future. In the meantime, I'm going to close this issue but thanks for reporting it! :smile:
