### ISSUE TITLE
Make it possible to only tweet the commit title

### ISSUE THREAD

**Issue by annevk** [github/github-services#1086]
As evidenced from https://twitter.com/htmlstandard tweets get rather verbose and yet still incomplete due to the 140 character limit. It would be better if there was an option to tweet just the commit URL and commit title, requiring a click for the rest of the details.

**Comment by annevk** [comment]
Fixing this might make fixing #964 unnecessary.

**Comment by pengwynn** [comment]
Thanks for the suggestion, @annevk. Since [we're only accepting security patches or major bug fixes][contrib], I'd suggest looking into a custom [webhook][] to get the behavior you want.

[contrib]: https://github.com/github/github-services/blob/master/CONTRIBUTING.md#updating-an-existing-service
[webhook]: https://developer.github.com/webhooks/
