### ISSUE TITLE
Amazon SNS messages too large

### ISSUE THREAD

**Issue by Rostepher** [github/github-services#1091]
# Problem

We've run into an issue recently where an Amazon SNS hook for a repo sent a push event message that was too large (333K), SNS messages have a [maximum size of 256K](https://docs.aws.amazon.com/sns/latest/dg/large-payload-raw-message.html). We have an internal application that listens to events for a number of our company's repos and relays the messages through SNS. The application has missed a number of events because of this unexpected interaction between the SNS message size limit and Github. Missed events have caused a number of subtle bugs in our application that went unnoticed until now.

# Possible Solution

Check the size of an SNS message before sending it. If the size exceeds 256K, send some form of error message explaining that the message size exceeded 256K and include a url to the actual event. This would shift the responsibility to the client to get the event from github and process it.

**Comment by keavy** [comment]
Thanks @Rostepher for the clear explanation and proposed possible solution! We'd be happy to see a PR to solve this, as we're only accepting PRs [for bug fixes or security patches](https://github.com/github/github-services/blob/master/CONTRIBUTING.md#updating-an-existing-service).

**Comment by mikemcquaid** [comment]
@Rostepher Any thoughts on the PR? If you're not interested or need a hand: let me know. Thanks!

**Comment by damtur** [comment]
Hey @mikemcquaid 
I might need some help.
So far my proposition is to check size of the payload prior to sending messages through SNS.

https://github.com/github/github-services/compare/github:master...hudl:AmazonSNSMessagesTooLargeFix

Problems:
1. How to check sns msg size reliably? We need to check byte size as in (http://docs.aws.amazon.com/sdkforruby/api/Aws/SNS/Client.html#publish-instance_method) - `bytesize` doesn't sound very good
2. Where can I find url which will be send through sns to make pooling easier (I thought it will be somewhere in `service.rb` but couldn't locate any
3. I don't like hardcoding sns message size, but given that we are using locked version of aws-sdk then that might be right?

Another solution may require us to check exception from `Aws:SNS::Client.publish()` but I think this is a rabbit hole, and might impact to many users using api.

**Comment by mikemcquaid** [comment]
> bytesize doesn't sound very good

Can you explain why `bytesize` doesn't sound good? It makes sense to me.

> 2. Where can I find url which will be send through sns to make pooling easier (I thought it will be somewhere in service.rb but couldn't locate any

Is this what you're looking for? https://github.com/github/github-services/blob/e38ed971baa6e32eca168e4e254c41e9eb2a67a4/lib/services/amazon_sns.rb#L12

@davidkelley may be able to help here.

> 3. I don't like hardcoding sns message size, but given that we are using locked version of aws-sdk then that might be right?

That could be OK as long as there's a test that will fail if the message size is changed.

**Comment by damtur** [comment]
Thx @mikemcquaid 
* bytesize - ok
* message size - ok
* url - the point is that client should know where it needs to get payload from
e.g. when you hit `GET /repos/:owner/:repo/pulls` one of the result value is `"url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347",` which tells you how to get same result.
My intentions here is to return GitHub API url where you can retrieve exacly same message as the one which cannot go through SNS as beeing too big. Any thoughts on that?

**Comment by davidkelley** [comment]
Hi @damtur, this is an odd issue and one that we've not encountered yet. I understand from the issue that in the case of an error, the hook should pass through a URL to the original hook payload, so that a client can retrieve the data. @mikemcquaid would this only work for public repositories though? I imagine the hook URL would also need to contain some sort of authentication otherwise.

**Comment by kdaigle** [comment]
> My intentions here is to return GitHub API url where you can retrieve exacly same message as the one which cannot go through SNS as beeing too big.

There isn't a way currently to get the exact hook payload programmatically. You can get the same resources for most payloads (like repository, actor, etc) via their API URLs though.

**Comment by damtur** [comment]
@davidkelley Yes, I want to have a way in client which listens for sns messages to have possibility to ask GitHub for the update directly. I thought that URL will be perfect and user friendly.
We have encountered problem with missing push/pull requests updates and now we know that the limit 256k is the problem for us.

@kdaigle :disappointed: If there is no way, how can we solve that problem? I need to uniquely identify the resource I want to keep my client up to date with GitHub. Is there a way of identification which payload we need?

And unfortunately I can't register GitHub hook directly as GitHub does not have access to my client, but I can access GitHub from my client. This is why we have used SNS messages.

**Comment by kdaigle** [comment]
@damtur in your specific use case, could you get an OAuth access token that could hit the API where authentication would be required? Let me keep thinking on our side to see if there is something we can do.

**Comment by davidkelley** [comment]
If you're often receiving messages that are larger than 256kb, perhaps SNS is not the best webhook to use. If I may suggest an easy alternative:

Github allows you to create webhooks that can be signed with a [shared secret](https://developer.github.com/webhooks/#payloads). The HMAC Digest of the payload is present inside the `X-Hub-Signature` header. If you're able to create a HTTPS internet-facing endpoint that Github can post webhooks to, it would be easy enough to verify the request (with the shared secret) using a simple script and then _pass_ the request on to your internal application.

**Comment by damtur** [comment]
@kdaigle 
If I understand you correctly you want me to add direct GitHub hook in my repos?
Well I possibly _could_ but that would require, tones of changes like manually update to all our repos to add GitHub hooks, white listing GitHub IP address in all our production servers - which is not only painful but also dangerous as we are not sure if you (GitHub) will not change your IP address, and writing support for new type of hook (GitHub instead of SNS).
So potentially this IS possible but God help me with convincing my colleagues that this is the Only and correct way of solving that problem.
I think even returning repo + event (like push/pull request etc) and error via sns will be more helpfull then not sending message at all.

@davidkelley Yes I'm aware of that possibility but we are not receiving less then 1% of messages, but it still causes degraded usage as it's not reliable. Also see above.
We are using shared secret and GitHub api with one of our repo so I know what you are talking about.

**Comment by damtur** [comment]
Another thing is it would become necessary for me to figure out how to make message delivery reliable across my client restarts or crashes.
SNS has a retry policy so that if my client is offline for a short amount of time, it will still get GitHub notifications when it comes back. I'm not sure that this is true for GitHub hook.

**Comment by Rostepher** [comment]
Maybe it would be worth splitting the payload into multiple parts if it exceeds the maximum size limit. Each part would need to be annotated with some ordering information, but this should side-step the problem of authentication.

**Comment by Rostepher** [comment]
I've implemented a solution to the problem and made a PR #1105. I'm open to suggestions and improvements.

**Comment by mikemcquaid** [comment]
Thanks @damtur and @Rostepher. The fix in https://github.com/github/github-services/issues/1105 was merged and deployed to production.
