### ISSUE TITLE
Form fields are not being validated

### ISSUE THREAD

**Issue by aw** [github/github-services#962]
Hi,

It appears the form validation is not working on any of the web services.

I was able to successfully add multiple services (active/not active) without entering any form data or seeing any error messages. It seems like a bug may have been introduced somewhere, perhaps in a recent merge?

**Comment by kdaigle** [comment]
I don't believe services ever had real validations setup. Each service implements required data in their own way so doing a form validation would require us to make a pretty significant change.

I imagine this became more obvious once we released the newer webhooks which has better form validation. Webhooks are much easier to make changes since we control the interface completely there.

I'm going to take this request and share it with the larger team but I'm going to close this issue out as it's not actionable directly within `github-services`. Thanks for the feedback! :sparkles:

**Comment by aw** [comment]
Yep I noticed that as well, which is why I never followed-up. Should have closed this a long time ago.

Thanks for the reply!
